#!/usr/bin/env bash

set -euo pipefail

SCRIPT_NAME="$(basename "$0")"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SOFTWARE_ROOT="$REPO_ROOT/areas/software"
MODULES_ROOT="$SOFTWARE_ROOT/modules"
FLAT_ROOT="$SOFTWARE_ROOT/flat"

FORMAT="all"
DRY_RUN=false
INSTALL_AGENTS_MD=false
SOURCE_DIRS=(rules skills workflows prompts)
TARGET_ROOTS=()

usage() {
  cat <<USAGE
Software Area Installer

Usage:
  $SCRIPT_NAME list [modules|flat]
  $SCRIPT_NAME install --module <name> --target <dir> [options]
  $SCRIPT_NAME install --flat <name|path> --target <dir> [options]
  $SCRIPT_NAME install --source <path> --target <dir> [options]

Options:
  --module           Module name from areas/software/modules (e.g. frontend)
  --flat             Flat package name from areas/software/flat (e.g. frontend) or explicit path
  --source           Explicit source directory
  -t, --target       Target project directory (can be provided multiple times)
      --targets      Comma-separated list of target directories
  -f, --format       Target format:
                     kilocode | antigravity | cursor |
                     agents | claude | codex | opencode |
                     both | all (default: all)
  -d, --dry-run      Show what would be copied
  -h, --help         Show this help

Examples:
  $SCRIPT_NAME list modules
  $SCRIPT_NAME install --module backend --target ./my-project --format all
  $SCRIPT_NAME install --flat frontend --target ./my-project --format codex
  $SCRIPT_NAME install --source ./areas/software/modules/backend --target . --format kilocode --dry-run
  $SCRIPT_NAME install --module backend --targets ./apps/front_module,./apps/back_module --format all
USAGE
}

log() {
  echo "[installer] $1"
}

list_modules() {
  find "$MODULES_ROOT" -mindepth 1 -maxdepth 1 -type d -exec basename {} \; | sort
}

list_flat() {
  find "$FLAT_ROOT" -mindepth 1 -maxdepth 1 -type d -exec basename {} \; | sort
}

print_find_results() {
  local search_dir="$1"
  local find_depth_args="$2"
  local filename_pattern="$3"
  local mode="$4"
  local results=""

  if [ ! -d "$search_dir" ]; then
    echo "- (none)"
    return
  fi

  if [ "$mode" = "basename" ]; then
    # shellcheck disable=SC2086
    results="$(find "$search_dir" $find_depth_args -type f -name "$filename_pattern" -exec basename {} \; | sort)"
  else
    # shellcheck disable=SC2086
    results="$(find "$search_dir" $find_depth_args -type f -name "$filename_pattern" | sed "s#^$search_dir/##" | sort)"
  fi

  if [ -z "$results" ]; then
    echo "- (none)"
    return
  fi

  while IFS= read -r line; do
    [ -n "$line" ] && echo "- $line"
  done <<< "$results"
}

copy_dir() {
  local src="$1"
  local dest="$2"

  if [ "$DRY_RUN" = true ]; then
    log "DRY-RUN: cp -a $src -> $dest/"
  else
    cp -a "$src" "$dest/"
  fi
}

copy_tree_targets() {
  local target_path="$1"
  local src_dir

  if [ "$DRY_RUN" = false ]; then
    mkdir -p "$target_path"
  fi

  for src_dir in "${SOURCE_DIRS[@]}"; do
    local src_path="$PACKAGE_PATH/$src_dir"

    if [ -d "$src_path" ]; then
      log "Copying $src_dir → $target_path"
      copy_dir "$src_path" "$target_path"
    else
      log "Skipping $src_dir (not found)"
    fi
  done
}

render_agents_md() {
  local out_file="$1"

  if [ "$DRY_RUN" = false ]; then
    mkdir -p "$(dirname "$out_file")"
  fi

  if [ -f "$PACKAGE_PATH/AGENTS.md" ]; then
    if [ "$DRY_RUN" = true ]; then
      log "DRY-RUN: cp -a $PACKAGE_PATH/AGENTS.md -> $out_file"
    else
      cp -a "$PACKAGE_PATH/AGENTS.md" "$out_file"
    fi
    return
  fi

  if [ -f "$PACKAGE_PATH/templates/AGENTS.md" ]; then
    if [ "$DRY_RUN" = true ]; then
      log "DRY-RUN: cp -a $PACKAGE_PATH/templates/AGENTS.md -> $out_file"
    else
      cp -a "$PACKAGE_PATH/templates/AGENTS.md" "$out_file"
    fi
    return
  fi

  local package_name
  package_name="$(basename "$PACKAGE_PATH")"

  log "No AGENTS.md found. Generating fallback AGENTS.md from source folders."

  if [ "$DRY_RUN" = true ]; then
    log "DRY-RUN: generate fallback $out_file"
    return
  fi

  {
    echo "# AGENTS.md"
    echo
    echo "Generated by $SCRIPT_NAME from source: $package_name."
    echo
    echo "## Rules"
    print_find_results "$PACKAGE_PATH/rules" "-maxdepth 1" "*.md" "basename"
    echo
    echo "## Skills"
    print_find_results "$PACKAGE_PATH/skills" "-mindepth 1 -maxdepth 2" "SKILL.md" "relative"
    echo
    echo "## Workflows"
    print_find_results "$PACKAGE_PATH/workflows" "-maxdepth 1" "*.md" "basename"
    echo
    echo "## Prompts"
    print_find_results "$PACKAGE_PATH/prompts" "-maxdepth 1" "*.md" "basename"
  } > "$out_file"
}

add_targets() {
  local raw_targets="$1"
  local item

  IFS=',' read -r -a split_targets <<< "$raw_targets"
  for item in "${split_targets[@]}"; do
    item="${item#${item%%[![:space:]]*}}"
    item="${item%${item##*[![:space:]]}}"
    [ -n "$item" ] && TARGET_ROOTS+=("$item")
  done
}

resolve_source() {
  if [ -n "${SOURCE_PATH:-}" ]; then
    PACKAGE_PATH="$SOURCE_PATH"
    return
  fi

  if [ -n "${MODULE_NAME:-}" ]; then
    PACKAGE_PATH="$MODULES_ROOT/$MODULE_NAME"
    return
  fi

  if [ -n "${FLAT_NAME:-}" ]; then
    if [ -d "$FLAT_NAME" ]; then
      PACKAGE_PATH="$FLAT_NAME"
      return
    fi

    PACKAGE_PATH="$FLAT_ROOT/$FLAT_NAME"
    return
  fi

  echo "Error: provide one source via --module, --flat, or --source."
  usage
  exit 1
}

if [ $# -eq 0 ]; then
  usage
  exit 1
fi

COMMAND="$1"
shift

case "$COMMAND" in
  list)
    LIST_TARGET="${1:-all}"
    case "$LIST_TARGET" in
      modules) list_modules ;;
      flat) list_flat ;;
      all)
        echo "Modules:" && list_modules
        echo
        echo "Flat packages:" && list_flat
        ;;
      *)
        echo "Unknown list target: $LIST_TARGET"
        exit 1
        ;;
    esac
    exit 0
    ;;
  install)
    ;;
  -h|--help)
    usage
    exit 0
    ;;
  *)
    usage
    exit 1
    ;;
esac

while [[ $# -gt 0 ]]; do
  case "$1" in
    --module)
      MODULE_NAME="$2"
      shift 2
      ;;
    --flat)
      FLAT_NAME="$2"
      shift 2
      ;;
    --source)
      SOURCE_PATH="$2"
      shift 2
      ;;
    -t|--target)
      TARGET_ROOTS+=("$2")
      shift 2
      ;;
    --targets)
      add_targets "$2"
      shift 2
      ;;
    -f|--format)
      FORMAT="$2"
      shift 2
      ;;
    -d|--dry-run)
      DRY_RUN=true
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1"
      usage
      exit 1
      ;;
  esac
done

resolve_source

if [ "${#TARGET_ROOTS[@]}" -eq 0 ]; then
  echo "Error: --target is required."
  usage
  exit 1
fi

if [ ! -d "$PACKAGE_PATH" ]; then
  echo "Error: source directory not found: $PACKAGE_PATH"
  exit 1
fi

case "$FORMAT" in
  antigravity)
    TARGET_SUB_DIRS=(.agent)
    ;;
  kilocode)
    TARGET_SUB_DIRS=(.kilocode)
    ;;
  cursor)
    TARGET_SUB_DIRS=(.cursor)
    ;;
  agents|claude|codex|opencode)
    TARGET_SUB_DIRS=()
    INSTALL_AGENTS_MD=true
    ;;
  both)
    TARGET_SUB_DIRS=(.agent .kilocode)
    ;;
  all)
    TARGET_SUB_DIRS=(.agent .kilocode .cursor)
    INSTALL_AGENTS_MD=true
    ;;
  *)
    echo "Invalid format: $FORMAT"
    exit 1
    ;;
esac

log "Installing source: $PACKAGE_PATH"
log "Target projects: ${TARGET_ROOTS[*]}"
log "Format: $FORMAT"
log "Dry-run: $DRY_RUN"

for target_root in "${TARGET_ROOTS[@]}"; do
  for target in "${TARGET_SUB_DIRS[@]:-}"; do
    [ -z "$target" ] && continue
    copy_tree_targets "$target_root/$target"
  done

  if [ "${INSTALL_AGENTS_MD:-false}" = true ]; then
    log "Rendering AGENTS.md → $target_root/AGENTS.md"
    render_agents_md "$target_root/AGENTS.md"
  fi
done

log "Done."
