#!/usr/bin/env bash

set -euo pipefail

SCRIPT_NAME="$(basename "$0")"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
AGENTOS_ROOT="$REPO_ROOT/agentos"

FORMAT="all"
DRY_RUN=false
INSTALL_AGENTS_MD=false
SOURCE_DIRS=(rules skills workflows prompts)

usage() {
  cat <<USAGE
AgentOS Installer

Usage:
  $SCRIPT_NAME list [domains|packages]
  $SCRIPT_NAME install --domain <name> --target <dir> [options]
  $SCRIPT_NAME install --package <name|path> --target <dir> [options]
  $SCRIPT_NAME install --source <path> --target <dir> [options]

Options:
  --domain           Domain name from agentos/domains (e.g. frontend)
  --package          Package name from agentos/packages (e.g. agent-os-frontend) or explicit path
  --source           Explicit source directory (contains rules/skills/workflows/prompts)
  -t, --target       Target project directory
  -f, --format       Target format:
                     kilocode | antigravity | cursor |
                     agents | claude | codex | opencode |
                     both | all (default: all)
  -d, --dry-run      Show what would be copied
  -h, --help         Show this help

Examples:
  $SCRIPT_NAME list domains
  $SCRIPT_NAME install --domain backend --target ./my-project --format all
  $SCRIPT_NAME install --package agent-os-frontend --target ./my-project --format codex
  $SCRIPT_NAME install --source ./agentos/domains/backend --target . --format kilocode --dry-run
USAGE
}

log() {
  echo "[agentos] $1"
}

list_domains() {
  find "$AGENTOS_ROOT/domains" -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | sort
}

list_packages() {
  find "$AGENTOS_ROOT/packages" -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | sort
}

copy_dir() {
  local src="$1"
  local dest="$2"

  if [ "$DRY_RUN" = true ]; then
    log "DRY-RUN: cp -a $src -> $dest/"
  else
    cp -a "$src" "$dest/"
  fi
}

copy_tree_targets() {
  local target_path="$1"
  local src_dir

  if [ "$DRY_RUN" = false ]; then
    mkdir -p "$target_path"
  fi

  for src_dir in "${SOURCE_DIRS[@]}"; do
    local src_path="$PACKAGE_PATH/$src_dir"

    if [ -d "$src_path" ]; then
      log "Copying $src_dir → $target_path"
      copy_dir "$src_path" "$target_path"
    else
      log "Skipping $src_dir (not found)"
    fi
  done
}

render_agents_md() {
  local out_file="$1"

  if [ "$DRY_RUN" = false ]; then
    mkdir -p "$(dirname "$out_file")"
  fi
  local package_name
  package_name="$(basename "$PACKAGE_PATH")"

  if [ -f "$PACKAGE_PATH/AGENTS.md" ]; then
    if [ "$DRY_RUN" = true ]; then
      log "DRY-RUN: cp -a $PACKAGE_PATH/AGENTS.md -> $out_file"
    else
      cp -a "$PACKAGE_PATH/AGENTS.md" "$out_file"
    fi
    return
  fi

  if [ -f "$PACKAGE_PATH/templates/AGENTS.md" ]; then
    if [ "$DRY_RUN" = true ]; then
      log "DRY-RUN: cp -a $PACKAGE_PATH/templates/AGENTS.md -> $out_file"
    else
      cp -a "$PACKAGE_PATH/templates/AGENTS.md" "$out_file"
    fi
    return
  fi

  log "No AGENTS.md template found. Building a fallback AGENTS.md from package folders."

  if [ "$DRY_RUN" = true ]; then
    log "DRY-RUN: generate fallback $out_file"
    return
  fi

  {
    echo "# AGENTS.md"
    echo
    echo "Generated by agentos-install.sh from source: $package_name."
    echo
    echo "## Rules"
    [ -d "$PACKAGE_PATH/rules" ] && find "$PACKAGE_PATH/rules" -maxdepth 1 -type f -name '*.md' -printf '- %f\n' | sort || echo "- (none)"
    echo
    echo "## Skills"
    [ -d "$PACKAGE_PATH/skills" ] && find "$PACKAGE_PATH/skills" -mindepth 1 -maxdepth 2 -type f -name 'SKILL.md' -printf '- %P\n' | sort || echo "- (none)"
    echo
    echo "## Workflows"
    [ -d "$PACKAGE_PATH/workflows" ] && find "$PACKAGE_PATH/workflows" -maxdepth 1 -type f -name '*.md' -printf '- %f\n' | sort || echo "- (none)"
    echo
    echo "## Prompts"
    [ -d "$PACKAGE_PATH/prompts" ] && find "$PACKAGE_PATH/prompts" -maxdepth 1 -type f -name '*.md' -printf '- %f\n' | sort || echo "- (none)"
  } > "$out_file"
}

resolve_source() {
  if [ -n "${SOURCE_PATH:-}" ]; then
    PACKAGE_PATH="$SOURCE_PATH"
    return
  fi

  if [ -n "${DOMAIN_NAME:-}" ]; then
    PACKAGE_PATH="$AGENTOS_ROOT/domains/$DOMAIN_NAME"
    return
  fi

  if [ -n "${PACKAGE_NAME:-}" ]; then
    if [ -d "$PACKAGE_NAME" ]; then
      PACKAGE_PATH="$PACKAGE_NAME"
      return
    fi

    PACKAGE_PATH="$AGENTOS_ROOT/packages/$PACKAGE_NAME"
    return
  fi

  echo "Error: provide one source via --domain, --package, or --source."
  usage
  exit 1
}

if [ $# -eq 0 ]; then
  usage
  exit 1
fi

COMMAND="$1"
shift

case "$COMMAND" in
  list)
    LIST_TARGET="${1:-all}"
    case "$LIST_TARGET" in
      domains) list_domains ;;
      packages) list_packages ;;
      all)
        echo "Domains:" && list_domains
        echo
        echo "Packages:" && list_packages
        ;;
      *)
        echo "Unknown list target: $LIST_TARGET"
        exit 1
        ;;
    esac
    exit 0
    ;;
  install)
    ;;
  -h|--help)
    usage
    exit 0
    ;;
  *)
    usage
    exit 1
    ;;
esac

while [[ $# -gt 0 ]]; do
  case "$1" in
    --domain)
      DOMAIN_NAME="$2"
      shift 2
      ;;
    -p|--package)
      PACKAGE_NAME="$2"
      shift 2
      ;;
    --source)
      SOURCE_PATH="$2"
      shift 2
      ;;
    -t|--target)
      TARGET_ROOT="$2"
      shift 2
      ;;
    -f|--format)
      FORMAT="$2"
      shift 2
      ;;
    -d|--dry-run)
      DRY_RUN=true
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1"
      usage
      exit 1
      ;;
  esac
done

resolve_source

if [ -z "${TARGET_ROOT:-}" ]; then
  echo "Error: --target is required."
  usage
  exit 1
fi

if [ ! -d "$PACKAGE_PATH" ]; then
  echo "Error: source directory not found: $PACKAGE_PATH"
  exit 1
fi

case "$FORMAT" in
  antigravity)
    TARGET_SUB_DIRS=(.agent)
    ;;
  kilocode)
    TARGET_SUB_DIRS=(.kilocode)
    ;;
  cursor)
    TARGET_SUB_DIRS=(.cursor)
    ;;
  agents|claude|codex|opencode)
    TARGET_SUB_DIRS=()
    INSTALL_AGENTS_MD=true
    ;;
  both)
    TARGET_SUB_DIRS=(.agent .kilocode)
    ;;
  all)
    TARGET_SUB_DIRS=(.agent .kilocode .cursor)
    INSTALL_AGENTS_MD=true
    ;;
  *)
    echo "Invalid format: $FORMAT"
    exit 1
    ;;
esac

log "Installing source: $PACKAGE_PATH"
log "Target project: $TARGET_ROOT"
log "Format: $FORMAT"
log "Dry-run: $DRY_RUN"

for target in "${TARGET_SUB_DIRS[@]:-}"; do
  [ -z "$target" ] && continue
  copy_tree_targets "$TARGET_ROOT/$target"
done

if [ "${INSTALL_AGENTS_MD:-false}" = true ]; then
  log "Rendering AGENTS.md → $TARGET_ROOT/AGENTS.md"
  render_agents_md "$TARGET_ROOT/AGENTS.md"
fi

log "Done."
